version: '3'

services:
  frontend-builder:
    build:
      context: ./frontend
    image: frontend-builder

  backend:
    build: ./backend
    expose:
      - "3000"

  nginx:
    build:
      context: ./nginx
    depends_on:
      - frontend-builder
      - backend
