services:
  frontend-builder:
    build:
      context: ./frontend
    image: frontend-builder

  backend:
    build: ./backend
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend-builder
